### ISSUE TITLE
 Internal Server Error: Missing `secret_token` and `secret_key_base` for 'development' environment

### ISSUE THREAD

**Issue by jacqueline-homan** [railschallenge/railschallenge-city-watch#7]

**Comment by jacqueline-homan** [comment]
I tried running the command `rake secret` but still no-go.

**Comment by railschallenge** [comment]
Working on recreating it now. Anything unusual about your setup? Running on Windows by chance?

**Comment by railschallenge** [comment]
Our bad. Thought that `rake secret` would regenreate the `config/secrets.yml` file, but all it does is spit out a new secret such as: `eb53e93638b6595f6ff27400c3a8...`

Will add a `config/secrets.yml` file to the repo for anyone else that runs into this issue.

**Comment by jacqueline-homan** [comment]
Hell NO I am not running this on Windows! I only dev on Linux. My other Rails and Ruby programs seem to be fine, my RVM has been updated, and no problems with that. My PATH is fine (I already checked), so....

**Comment by railschallenge** [comment]
lol - fair enough on the Windows end and :thumbsup: for Linux.

Just an oversight. @jefflunt added a file that should work just now. Let us know if you run into additional problems. Thanks for the report.
